version: '3.8'

services:
  app:
    image: ghcr.io/chung2310/igen-landing-page:${IMAGE_TAG:-develop}
    container_name: ${CONTAINER_NAME:-igen-ldp-staging}
    restart: always
    ports:
      - "${PORT:-5001}:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - default_network
networks:
  default_network:
    external: true